// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/model","name":"model","icon":"smile","layout":false,"id":"1"},"2":{"path":"/ros","name":"ros","icon":"appstore","parentId":"ant-design-pro-layout","id":"2"},"3":{"path":"/online","name":"online","icon":"desktop","parentId":"ant-design-pro-layout","id":"3"},"4":{"path":"/","redirect":"/ros","parentId":"ant-design-pro-layout","id":"4"},"5":{"path":"*","layout":false,"id":"5"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true},"umi/plugin/openapi":{"path":"/umi/plugin/openapi","id":"umi/plugin/openapi"}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "p__RobotModelStudio__index" */'@/pages/RobotModelStudio/index.jsx')),
'2': React.lazy(() => import(/* webpackChunkName: "p__Ros__index" */'@/pages/Ros/index.jsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__RobotModelStudio__index" */'@/pages/RobotModelStudio/index.jsx')),
'4': React.lazy(() => import( './EmptyRoute')),
'5': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "umi__plugin-layout__Layout" */'D:/ant-design-pro/ant-design-pro-master/ant-design-pro-master/src/.umi/plugin-layout/Layout.tsx')),
'umi/plugin/openapi': React.lazy(() => import(/* webpackChunkName: "umi__plugin-openapi__openapi" */'D:/ant-design-pro/ant-design-pro-master/ant-design-pro-master/src/.umi/plugin-openapi/openapi.tsx')),
},
  };
}
