// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from 'D:/ant-design-pro/ant-design-pro-master/ant-design-pro-master/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import AppstoreOutlined from 'D:/ant-design-pro/ant-design-pro-master/ant-design-pro-master/node_modules/@ant-design/icons/es/icons/AppstoreOutlined';
import DesktopOutlined from 'D:/ant-design-pro/ant-design-pro-master/ant-design-pro-master/node_modules/@ant-design/icons/es/icons/DesktopOutlined';
export default { SmileOutlined, AppstoreOutlined, DesktopOutlined };
